version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

